### PR TITLE
Some small tweaks to the build system

### PR DESCRIPTION
**Pull request by the1derer**
Please merge [typetools/guava:master](https://github.com/typetools/guava) to [eisop/guava:master](https://github.com/eisop/guava) before reviewing or merging this PR.

This PR contains changes to implement [eisop/checker-framework#32](https://github.com/eisop/checker-framework/pull/32) and [eisop/checker-framework#34](https://github.com/eisop/checker-framework/pull/34)

Thanks.

### CODE REVIEW

**Comment by wmdietl** [comment]
@the1derer I merged typetools/guava into eisop/guava. Can you please update this PR?

**Comment by the1derer** [comment]
> @the1derer I merged typetools/guava into eisop/guava. Can you please update this PR?

@wmdietl Done

**Comment by wmdietl** [comment]
Thanks!

**Pull request merged**
